### ISSUE TITLE
Some bugs and error

### ISSUE THREAD

**Issue by ymomfe** [DeltaNedas/recipe-lib#1]
1) in `require` require the wrong path to the script file.
2) TypeError: Cannot read property "0" from underfined (defs#74)
Crash report:
```
org.mozilla.javascript.EcmaError: TypeError: Cannot read property "0" from undefined (defs#74)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4256)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4234)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4267)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4286)
	at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:4298)
	at org.mozilla.javascript.ScriptRuntime.getObjectElem(ScriptRuntime.java:1526)
	at org.mozilla.javascript.gen.defs_9._c_anonymous_8(defs:74)
	at org.mozilla.javascript.gen.defs_9.call(defs)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:409)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3566)
	at org.mozilla.javascript.gen.defs_9.call(defs)
	at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:613)
	at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:594)
	at adapter4.valid(<adapter>)
	at mindustry.world.modules.ConsumeModule.update(ConsumeModule.java:35)
	at mindustry.entities.type.TileEntity.update(TileEntity.java:331)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:51)
	at mindustry.core.Logic.update(Logic.java:241)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:138)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
```
(Crash when i place Scrap Factory)

**Comment by Fatonndev** [comment]
![image](https://user-images.githubusercontent.com/56699208/77137575-8ac86080-6a7f-11ea-8131-6f98a89465c1.png)
The same thing, the script does not see recipes.

**Comment by deltanedas** [comment]
abandoned
